### ISSUE TITLE
Allow users to edit the templates of security groups, networks, and resources

### ISSUE THREAD

**Issue by promiseu77** [hortonworks/cloudbreak#1208]
Allow users to edit the templates of security groups, networks, and resources.

It is not possible right now. Cloudbreak 1.1.0 is the latest version at this moment.

Thanks

**Comment by doktoric** [comment]
hello @promiseu77,
In that case if you can edit for example a security group and that security group used by a cluster then you have to modify that cluster as well, which is quite hard to solve. For example you have a resource on azure which is D4 and you modify that template to D5 than you have to migrate the whole cluster for D5 instances. This function is not supported by every cloud provider.

**Comment by nsteinmetz** [comment]
On this topic, the possibility at least to create a new security group by duplicating an existing one and adding new rules would be enough I think.

Startiing from scratch is a lillte bit messy.

**Comment by doktoric** [comment]
@nsteinmetz 
I will add these 'clone and modify existing one' feature to the next release
Br
R

**Comment by lacikaaa** [comment]
outdated, we don't have templates for these resources
