### ISSUE TITLE
Error message after login

### ISSUE THREAD

**Issue by MariusDieckmann** [hortonworks/cloudbreak#2598]
After login screen appears the following error occurs on when loading the dashboard:
message	"Cannot retrieve token"
Version is 1.16.1
I followed the openstack manual installation guide using additional security settings as suggested in the documentation.
On first start after pulling the following error message occured:
ERROR: for logsink  Cannot start service logsink: Cannot start container 726a882288a85a5731308d2240d9420452d4d3e86ec5fe088ce4cf8094bae127: [8] System error: write /sys/fs/cgroup/devices/system.slice/docker-726a882288a85a5731308d2240d9420452d4d3e86ec5fe088ce4cf8094bae127.scope/cgroup.procs: no such device

ERROR: for commondb  Cannot start service commondb: Cannot start container 8f528a2f508ba24caa7187f8eed36a2a0b7ceecd71594559120c4a6f3af7eb52: lstat /dev/dm-3: no such file or directory

The second start attempt worked with no displayed errors.

**Comment by doktoric** [comment]
Hi @MariusDieckmann 
Which docker are using on the host?

**Comment by asmaier** [comment]
I have the same problem. It appeared after I stopped and restarted my VM on Amazon EC2. I tried to call 

```
cbd kill
cbd doctor
cbd regenerate
cbd start-wait 
```
After doing that I see the error message {"message":"Cannot retrieve csrf token"} . Do you have any idea on that?

**Comment by MariusDieckmann** [comment]
This is the used Docker version:
Docker version 1.9.1, build a34a1d5
i installed it as suggested in the docuentation
OS: CentOS Linux release 7.3.1611 (Core) 
Running as virtual machine in Openstack environment.
I saw the same error on 1.14.4. After approx. two weeks cloudbreak failed and i cloud not reach the WebUI although i could ssh into the machine. After updating to 1.16.1 it worked again...

**Comment by rafaleon15** [comment]
I found a trick trhat worked for me after I got to this error message.
Login using a wrong password so the error message is shown. After that login using the correct password. 

BR.

**Comment by prarthanabasgodumesh** [comment]
I have same problem now. the containers have been running for 5 months without any issue.now we are unable to login.

**Comment by mdotti** [comment]
I have the same problem, and running 'cbd ps' shows me:

cbreak_commondb_1 /docker-entrypoint.sh publication ... Exit 255

I do not know why the 'cbd start' command does not upload this.

Any suggestion?

**Comment by mhmxs** [comment]
Hi @mdotti ,

It is a known and fixed issue, but only on master branch. The problem is when you forget to execute cbd kill Cloudbreak deployer doesn't restart the database. Workaround is: execute `cbd kill` before stopping docker/docker machine or before `cbd start`. We have `cbd restart` command which also solves the problem.
