### ISSUE TITLE
CloudBreak should grant its service principal access to ADLS 

### ISSUE THREAD

**Issue by liupeirong** [hortonworks/cloudbreak#2610]
When CloudBreak configures ADLS access, it should also add its service principal to the ADLS account if the service principal has sufficient privilege in the Azure subscription where the ADLS account is located.  Otherwise, the cluster won't be able to access ADLS.

**Comment by pdarvasi** [comment]
Adding access for the service principal might take a long time if there is a large number of already existing files, as access must be granted individually for all of them. Therefore our initial solution is to warn the user, that she has to grant access (ACL) to the service principal manually after cluster creation. Plan is to support configuration for an existing Service Principal also.
