### ISSUE TITLE
Creating a cluster hangs at "update in progress: Infrastructure metadata collection finished"

### ISSUE THREAD

**Issue by asmaier** [hortonworks/cloudbreak#2639]
I try to create a Hadoop cluster on AWS from a cloudbreak VM hosted in my local network and it always hangs at "update in progress: Infrastructure metadata collection finished". The instances seem to have started on AWS, but it looks like they cannot connect to the cloudbreak VM to send information about their status. The ports 22 and 443 are open and reachable from the internet on my cloudbreak VM. But can it be, that cloudbreak needs more open ports than these two? If so, which ports need to be open and reachable from the internet on the cloudbreak VM? Or could there be another reason for this problem?

**Comment by doktoric** [comment]
@asmaier Are you using an existing AWS network ? Do your cloudbreak instance can reach those machines ? The cloudbreak instance try to ssh into those AWS instances after the provisioning. Is it possible that your local machine can not reach the vm's on amazon ?

**Comment by asmaier** [comment]
You were right. The VM was not able to reach the AWS instances. The problem was, that I had configured the wrong IP in my AWS security group. So the cloudbreak VM wasn't allowed to access the instances it created on AWS. Sorry for this unnecessary ticket.
