### ISSUE TITLE
Support glance v2 .

### ISSUE THREAD

**Issue by zhoutiekui** [hortonworks/cloudbreak#2649]
HI，all:
   I have used the cloudbreak with openstack, but it is only supports glance v1, which is depracated by the openstack commit. And the recommended glance API version is glance v2, which is already supported by OpenStack4j. So I want to know is there a plan to support glance v2,  thanks.

**Comment by sodre90** [comment]
Hi, we plan to support glance-v2 but we don't have ETA yet.
If you implement glance-v2 support, then we will happily merge your pull request :)

**Comment by pdarvasi** [comment]
@zhoutiekui The [PR](https://github.com/hortonworks/cloudbreak/pull/3068) has been merged and backported to 1.16.6 rc version, closing this, as resolved.
