### ISSUE TITLE
Execute shell script with arguments from CloudBreak Shell

### ISSUE THREAD

**Issue by riteshapatel** [hortonworks/cloudbreak#2831]
Hi,

Does CloudBreak Shell "script" command allow to execute script with arguments? If so what is the syntax? If it's not supported, then would it be possible to add that feature? 

Any input is appreciated.

Thx,

Ritesh

**Comment by mhmxs** [comment]
Hi @riteshapatel ,

What kind of script do you mean? Shell is an interactive shell which can execute cloudbreak commands one by one (interactively). If you collect your commands in a file, it can execute the commands one by one with --cmdfile flag.

**Comment by riteshapatel** [comment]
@mhmxs I am referring to shell script with arguments. For example, I want to pass in VpcId, Subnet CIDR etc to the shell script for automation. Is it possible? Seems like CloudBreak Shell does not recognize argument reference when parsing the shell commands one-by-one. 

e.g.

```shell
./create-cluster.sh vpc-123456 10.0.0.1/24 

```

Now with CloudBreak shell is this possible?

```shell
cloudbreak-shell-quiet < create-cluster.sh vpc-123456 10.0.0.1/24

```

And then refer to these arguments in the shell script

```shell

vpcId=$1
subnetCidr=$2

```

I tried but CloudBreak Shell is throwing errors. If I hardcode values then script runs fine without the arguments.

Thx,

Ritesh

**Comment by mhmxs** [comment]
Hi @riteshapatel ,

Not, because two reasons:
 * script file is a plain text file
 * shell parameter is a file name not a file "pointer"
