### ISSUE TITLE
GCP Image sequenceiqimage/hdc-hdp--1708301513.tar.gz Not Found (cbd 1.16.5)

### ISSUE THREAD

**Issue by egwada** [hortonworks/cloudbreak#2997]
We installed the latest Cloudbreak version **1.16.5** on Google Cloud Platform. We faced this error:

```
cloudbreak_1   | 2018-01-11 16:17:59,315 [reactorDispatcher-64] handleStackCreationFailure:231 ERROR c.s.c.c.f.s.p.a.StackCreationService - [owner:97ab50e9-7cef
-4483-86f2-8c8225c411c1] [type:STACK] [id:12] [name:test-1] Error during stack creation flow:
cloudbreak_1   | com.sequenceiq.cloudbreak.cloud.exception.CloudConnectorException: Error occurred on 12 stack during the setup: 404 Not Found
cloudbreak_1   | {
cloudbreak_1   |   “code” : 404,
cloudbreak_1   |   “errors” : [ {
cloudbreak_1   |     “domain” : “global”,
cloudbreak_1   |     “message” : “Not Found”,
cloudbreak_1   |     “reason” : “notFound”
cloudbreak_1   |   } ],
cloudbreak_1   |   “message” : “Not Found”
cloudbreak_1   | }
cloudbreak_1   |        at com.sequenceiq.cloudbreak.cloud.gcp.GcpProvisionSetup.prepareImage(GcpProvisionSetup.java:86)
cloudbreak_1   |        at com.sequenceiq.cloudbreak.cloud.handler.PrepareImageHandler.accept(PrepareImageHandler.java:47)
cloudbreak_1   |        at com.sequenceiq.cloudbreak.cloud.handler.PrepareImageHandler.accept(PrepareImageHandler.java:21)
cloudbreak_1   |        at com.sequenceiq.cloudbreak.cloud.handler.PrepareImageHandler$$FastClassBySpringCGLIB$$aaf961cd.invoke(<generated>)
cloudbreak_1   |        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
```

We spent some time to understand a such error ! We identified that the image Cloudbreak try to get from Google Cloud Storage bucket was not available in http://storage.googleapis.com/sequenceiqimage !
In fact the image defined in the 1.16.5 release - https://github.com/hortonworks/cloudbreak/blob/release-1.16/cloud-gcp/src/main/resources/gcp-images.yml - is not available !

Workaround 
Create a file gcp-images.yml on /var/lib/cloudbreak-deployment/etc  with a such content 

```
gcp:
  default: sequenceiqimage/hdc-hdp--1711171616.tar.gz
```

**Comment by ValentinOdier** [comment]
Same issue on Openstack

Could not find how to download image : hdc-hdp--1708301513

**Comment by pdarvasi** [comment]
@egwada  The following URL is accessible for me, could you please give it a try?
 https://storage.googleapis.com/sequenceiqimage/hdc-hdp--1708301513.tar.gz

@ValentinOdier Have you successfully completed the following steps?
http://hortonworks.github.io/cloudbreak-docs/latest/openstack/#import-the-image-into-your-openstack

**Comment by ValentinOdier** [comment]
Hi, nop. I can upload my image the issue is i can't download the image from your S3 bucket because it seems it does not exist (not tested since my last post). I'm also stuck anyway as only public image can currently be used on openstack. I am waiting the release of the fix/upgrade. I had the issue on more than version 1.16.5 but unfortunaly i did not keep track.

**Comment by pdarvasi** [comment]
@ValentinOdier That issue has already been fixed and backported, pls. check here:
https://community.hortonworks.com/questions/156952/cloudbreak-private-image-not-found-on-openstack.html?page=3&pageSize=10&sort=votes
