### ISSUE TITLE
OpenStack not listing private images

### ISSUE THREAD

**Issue by ValentinOdier** [hortonworks/cloudbreak#3056]
Hi,

I've been trying to deploy cloudbreak on a public openstack cloud but it does not work since i'm unable to upload hdc-hdp--XXX.img as a "public" image.

From what i have seen it looks like this is using the V1 of the image API.

code in github : https://github.com/hortonworks/cloudbreak/blob/9705848c6a29e706b6d35b4df0dc10e58b459bc7/cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackSetup.java#L82

This is using `image().listAll()` and this method will only list public image meaning i will never find my hdc-hdp--XXX.img  image since i can only upload "private" image (src = http://www.openstack4j.com/javadoc/org/openstack4j/api/image/ImageService.html#listAll--)

My knowledge of this project is limited  but i did try to change line 82 to `imageV2().list()` (updating the import too ofc) and i can build the project without any issue. (src = http://www.openstack4j.com/javadoc/org/openstack4j/api/image/v2/ImageService.html#list--)

How can i know i haven't broke anything ? Should i create a branch with my modification and submit a merge request ? 

ps : this could be linked to https://github.com/hortonworks/cloudbreak/issues/2649

Thanks for your help.

**Comment by mhmxs** [comment]
Hi @ValentinOdier ,

First of all thanks for the info and hopefully we should solve this error with your help.

"How can i know i haven't broke anything ?" Cross your fingers :D but apart of joke, what you can do is test your change on your environment with public and private images. If works you can execute `./gradlew build` to be sure everything is formally ok. Than you can create a pull request. Our basic tests are executing on pull requests. Someone will approve, and we have nightly tests on our openstack environment. So please feel free to send merge/pull request.

**Comment by ValentinOdier** [comment]
Ok thanks for the info.

ATM i am able to do a clean build but i haven't tried to run it yet. I'm not on mac and i'm a bit lost with instructions.

I will have a closer look and see if i can make it work

**Comment by akanto** [comment]
We have a pull request for this: https://github.com/hortonworks/cloudbreak/pull/3068

**Comment by ValentinOdier** [comment]
Hi, i sow this was even merged to master. I don't fully understand your release process yet. 

I would gladly try it but i seems i'm not getting a version with this fixed. Which cloudbreak-deployer should i be using to try it out ?

**Comment by mhmxs** [comment]
Hi @ValentinOdier ,

Deployer doesn't offer any unstable builds. You have to download manually by executing something like this:
```
curl -L s3.amazonaws.com/public-repo-1.hortonworks.com/HDP/cloudbreak/cloudbreak-deployer_snapshot_$(uname)_x86_64.tgz | tar -xz -C $(dirname $(which cbd))
```
