### ISSUE TITLE
Update new IP of compute on HDP Cluster to CloudBreak

### ISSUE THREAD

**Issue by technology20nn** [hortonworks/cloudbreak#3267]
- Version: cbd 2.4.1-rc.27
- I'm using cloudbreak setup HDP on GCP. When deploy done, i change ip of compute on Cluster. But on Cloudbreak not update to new IP of compute. And it can not comunicate with Cluster (Alway in status Update In Process).
How to update new IP of compute to CloudBreak?

**Comment by mhmxs** [comment]
Hi @technology20nn,
I doon't know the reason why did you change the IP address of the node, but changing underlying components is not supported by Cloudbreak. No one tests scenarios like this one. Some changes are percieveable by using `sync`, but most of them are not. Did you try to `sync` the cluster?

**Comment by technology20nn** [comment]
Hi @mhmxs ,
Because before i deploy cluster via cloudbreak. I has exist hadoop cluster run ingest som dbs. I has config firewall grant this ips cluster to access data. So, when i setup new cluster via cloudbreak, i want using previous IPs cluster to don't firewall. 
I hope cloudbreak will provide feature edit ips info via dashboard.

**Comment by mhmxs** [comment]
Hi @technology20nn ,
There are more options when you create a firewall rule next to IP ranges, for example filter by [service account](https://cloud.google.com/vpc/docs/firewalls#serviceaccounts) or (network tag)[https://cloud.google.com/vpc/docs/add-remove-network-tags]. I suggest to use one of them.
