### ISSUE TITLE
Hive ha cli error

### ISSUE THREAD

**Issue by regonzalo** [hortonworks/cloudbreak#3394]
When creating a cluster in HA from cli appears the following error message "Incorrect number of 'HIVE_SERVER' components are in '[master_2, master_3]". If the same cluster is launched from the UI, there is no problem.

**Comment by regonzalo** [comment]
cb --version
cb version 2.4.1-2018-04-05T09:40:24

**Comment by keyki** [comment]
Can you try to including the 
```
"validateBlueprint" : false
```
below the blueprintName json field?

**Comment by regonzalo** [comment]
Sorry for the delay, it worked perfectly with the proposed change. Thank you!
