### ISSUE TITLE
"ghost" instance in hostmetadata

### ISSUE THREAD

**Issue by thaibui** [hortonworks/cloudbreak#3529]
Currently, I'm seeing a bug where an AWS spot instance that were terminated but still exists in Cloudbreak internal table "hostmetadata" in an active hostgroup. This causes Cloudbreak to terminate healthy instances in the hostgroup when a resize request is issued. 

For example, let's say we have a cluster with a hostgroup that contains only 9 actual healthy + 2 "ghost" instance in hostmetadata. When a resize request to scale the hostgroup to 10 (because an internal process detected that there's only 9 healthy workers and we want 10 workers). When this happens, Cloudbreak will remove 1 random node in the hostgroup instead of the desired affect or adding 1.

I'm currently using 2.4.0. I just wonder if we have seen this bug before and is upgrading will fix it? If not, I will try to find sometime to reproduce the bug with a snapshot of the database and fix it.

**Comment by thaibui** [comment]
We have theorized that this happened because of a spot instance got deleted in aws, and our automation doesn't sync with cloudbreak right away within the next hour. 

Since aws instance's status won't be available after 1 hour of termination time, Cloudbreak won't be able to get the status of the terminated instance, this threw an exception (instance not found) causing Cloudbreak to swallow the exception without updating the hostmetadata's status from HEALTHY to TERMINATED and try again in the next hour. 

It's just a theory so I will test this one out once I have time and will submit a patch if possible.

**Comment by biharitomi** [comment]
Hi @thaibui ,
It could be, but if it is not a problem for you then please try to test/check it on 2.4.2 version. Because this AWS instance status related issue maybe fixed in the new 2.4.2 release.
If the issue still exists and you have enough time then we are happy to check your patch.

**Comment by thaibui** [comment]
thx, will do.

**Comment by akanto** [comment]
Expected to be fixed in 2.4.2, please reopen if you run into this issue
