### ISSUE TITLE
Blueprint creation page doesn't proceed once encounter an invalid json file

### ISSUE THREAD

**Issue by nsharma-git** [hortonworks/cloudbreak#3965]
Steps to reproduce 

1. Go to Blueprint section in Cloudbreak UI. 
2. Try to import an invalid Json File as blueprint. CB will throw out proper message.
3. Fix the json and try to import again.
No action if we push 'Create' button. There is no error message as well.

- Cloudbreak version - 2.7.2-rc.28
- Host platform - Cent OS 7

**Comment by tamasfoldi** [comment]
Hi @nsharma-git ,

I thanks for reporting the issue. We are going to fix it.

Best Regards,
Tamas

**Comment by lacikaaa** [comment]
fixed
