### ISSUE TITLE
[feature request] local SSD option for GCP

### ISSUE THREAD

**Issue by desaiak** [hortonworks/cloudbreak#410]
Would like to see option to add local SSD for GCP nodes. (https://cloud.google.com/compute/docs/local-ssd)
The feature is currently in BETA but expected to GA soon, also currently Local SSD is available in all zones except us-central1-b and europe-west1-a (which is deprecated).

**Comment by doktoric** [comment]
Hi @desaiak,
Are you interested in this with these restrictions below:
Local SSD has the following restrictions when compared to other block storage options:
- Limited create-time flexibility. Local SSDs must be created at the same time as the virtual machine instance.
- Limited reliability. Local SSDs are unreplicated and have no data redundancy.
- No snapshotting. Unlike persistent disks, local SSDs do not offer a snapshot feature.
- Limited disk-size flexibility. Local SSDs are 375 GB per device, and only four local SSD devices are allowed per instance.
- Restricted usage. Local SSDs cannot be used as root disks.

**Comment by desaiak** [comment]
Yes, I was planning on using the SSDs for transient data type applications which have inbuilt fault tolerance and availability eg. Kafka.
Just FYI .. currently this is not a very high priority to have for me.

**Comment by matyix** [comment]
Makes sense - we will add these quite soon, but just wanted to highlight that the local storage will not be suitable for `regular` Hadoop nodes (where you have several TB sized disks attached to a slave node).
