### ISSUE TITLE
CLI does not work properly if the password contains "-", tested on release-2.9.0

### ISSUE THREAD

**Issue by yuliu-sn** [hortonworks/cloudbreak#4705]
Could be a BUG:

- Cloudbreak version `2.9.0`
- Host platform: AWS/ amazon linux 2
- If the password contains a "-", (e.g., "aa-bbbbb1234" ) Cli will just give a error message said
  > ERROR: status code: 400, message: The length of the password has to be in range of 5 to 100  
- The specific shell command likes
  > cb cluster create --cli-input-json createcluster.json ...

**Comment by horadla23** [comment]
Hi @yuliu-sn!

Currently there are two fields, which has a size-validation like this. Could you tell us, was the field cluster/ambari/ambariSecurityMasterKey filled? 

Because if ambariSecurityMasterKey fields's value is not null and the length of it is invalid, that could also cause an error like that you mentioned.

**Comment by yuliu-sn** [comment]
Hi @horadla23, 
sorry for my late reply.
where is the file/field that you mentioned `cluster/ambari/ambariSecurityMasterKey`? 
Is it the one set when creating the cluster using CB? 

I created the cluster **successfully using the web console**  but CLI does not work appropriately when I tried to recreate the cluster.

**Comment by horadla23** [comment]
Hi @yuliu-sn!

You can download the CLI json from UI: https://docs.hortonworks.com/HDPDocuments/Cloudbreak/Cloudbreak-2.9.0/install-cli/content/cb_obtain-cluster-json-template-from-the-ui.html

With this you can compare the json of your cluster successfully created on UI and your json which you are using during cluster creation with CLI.

**Comment by yuliu-sn** [comment]
Thanks, yes, I did it exactly as you said before as posted. The json was downloaded from web ui (otherwise I don't even know how to write a complete one for a complicated cluster...).

**Comment by horadla23** [comment]
@yuliu-sn Cool, if it is working, then please close this issue. Thanks in advance!

**Comment by yuliu-sn** [comment]
@horadla23 ... the cli failed, so that I described it here: [link to above](https://github.com/hortonworks/cloudbreak/issues/4705#issue-418463766)

**Comment by horadla23** [comment]
Sorry, I misunderstood, in this case you should check the json, because when you download it from UI, the sensitive fields like passwords are cleared out due security reasons, so you need to check those field and fill them.

**Comment by yuliu-sn** [comment]
@horadla23 oh, yes it works now, thank you! the json is so long that couldn't find the empty password ... It would be great the UI can give some hints on this...
Anyway, I don't have a problem anymore.  Thanks!
